version: '3.8'

services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/
      - ./view:/usr/share/nginx/html/
    ports:
      - 80:80
  
  node:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9000:3000
    volumes:
      - ./app:/app
    command: > 
      bash -c "npm run dev"
    
    